import React from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { Shield, Lock, FileText, AlertCircle } from 'lucide-react';

const PrivacyPolicy = () => {
  // Current date for last updated display
  const lastUpdated = "September 15, 2025";
  
  return (
    <>
      <Navbar />

      {/* Hero Section */}
      <div className="px-4 sm:px-20 xl:px-32 pt-24 pb-16 bg-gradient-to-r from-blue-50 to-indigo-50 bg-cover bg-no-repeat">
        <div className="text-center mb-8">
          <h1 className="text-3xl sm:text-5xl md:text-6xl font-semibold leading-tight">
            Privacy <span className="text-primary">Policy</span>
          </h1>
          <p className="mt-4 max-w-2xl mx-auto text-gray-600">
            Last Updated: {lastUpdated}
          </p>
        </div>
      </div>

      {/* Introduction */}
      <div className="px-4 sm:px-20 xl:px-32 py-12 bg-white">
        <div className="max-w-3xl mx-auto">
          <div className="flex items-center gap-3 mb-6">
            <div className="bg-primary/10 p-2 rounded-full">
              <Shield className="w-5 h-5 text-primary" />
            </div>
            <h2 className="text-2xl font-semibold">Introduction</h2>
          </div>
          
          <div className="prose prose-lg max-w-none text-gray-700">
            <p>
              At QuickAI, we take your privacy seriously. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website or use our AI tools and services. Please read this privacy policy carefully. If you do not agree with the terms of this privacy policy, please do not access the site.
            </p>
            <p>
              We reserve the right to make changes to this Privacy Policy at any time and for any reason. We will alert you about any changes by updating the "Last Updated" date of this Privacy Policy. Any changes or modifications will be effective immediately upon posting the updated Privacy Policy on the site. You are encouraged to periodically review this Privacy Policy to stay informed of updates.
            </p>
          </div>
        </div>
      </div>

      {/* Collection of Information */}
      <div className="px-4 sm:px-20 xl:px-32 py-12 bg-gray-50">
        <div className="max-w-3xl mx-auto">
          <div className="flex items-center gap-3 mb-6">
            <div className="bg-primary/10 p-2 rounded-full">
              <FileText className="w-5 h-5 text-primary" />
            </div>
            <h2 className="text-2xl font-semibold">Collection of Your Information</h2>
          </div>
          
          <div className="prose prose-lg max-w-none text-gray-700">
            <p>
              We may collect information about you in a variety of ways. The information we may collect via the Site includes:
            </p>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">Personal Data</h3>
            <p>
              Personally identifiable information, such as your name, email address, and telephone number, that you voluntarily give to us when you register with the Site or when you choose to participate in various activities related to the Site, such as online chat and message boards. You are under no obligation to provide us with personal information of any kind, however, your refusal to do so may prevent you from using certain features of the Site.
            </p>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">Derivative Data</h3>
            <p>
              Information our servers automatically collect when you access the Site, such as your IP address, your browser type, your operating system, your access times, and the pages you have viewed directly before and after accessing the Site. If you are using our mobile application, this information may also include your device name and type, your operating system, your phone number, and other identifying information.
            </p>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">AI-Generated Content and Prompts</h3>
            <p>
              When you use our AI tools, we collect the prompts, inputs, and requests you provide to generate content. We also collect the content generated by our AI services in response to your prompts. This data is used to improve our AI models and provide better service to you.
            </p>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">Financial Data</h3>
            <p>
              Financial information, such as data related to your payment method (e.g., valid credit card number, card brand, expiration date) that we may collect when you purchase, order, or request information about our services. We store only very limited, if any, financial information that we collect. Otherwise, all financial information is stored by our payment processor, and you are encouraged to review their privacy policy and contact them directly for responses to your questions.
            </p>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">Third-Party Data</h3>
            <p>
              Information from third parties, such as personal information or network friends, if you connect your account to the third party and grant the Site permission to access this information.
            </p>
          </div>
        </div>
      </div>

      {/* Use of Information */}
      <div className="px-4 sm:px-20 xl:px-32 py-12 bg-white">
        <div className="max-w-3xl mx-auto">
          <div className="flex items-center gap-3 mb-6">
            <div className="bg-primary/10 p-2 rounded-full">
              <Lock className="w-5 h-5 text-primary" />
            </div>
            <h2 className="text-2xl font-semibold">Use of Your Information</h2>
          </div>
          
          <div className="prose prose-lg max-w-none text-gray-700">
            <p>
              Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the Site to:
            </p>
            
            <ul className="list-disc pl-6 my-4">
              <li>Create and manage your account.</li>
              <li>Process payments and refunds.</li>
              <li>Compile anonymous statistical data and analysis for use internally or with third parties.</li>
              <li>Deliver targeted advertising, newsletters, and other information regarding promotions to you.</li>
              <li>Email you regarding your account or order.</li>
              <li>Enable user-to-user communications.</li>
              <li>Generate a personal profile about you to make future visits to the Site more personalized.</li>
              <li>Increase the efficiency and operation of the Site.</li>
              <li>Monitor and analyze usage and trends to improve your experience with the Site.</li>
              <li>Prevent fraudulent transactions, monitor against theft, and protect against criminal activity.</li>
              <li>Resolve disputes and troubleshoot problems.</li>
              <li>Send you a newsletter with information and updates.</li>
              <li>Train and improve our AI models and algorithms.</li>
            </ul>
          </div>
        </div>
      </div>

      {/* Disclosure of Information */}
      <div className="px-4 sm:px-20 xl:px-32 py-12 bg-gray-50">
        <div className="max-w-3xl mx-auto">
          <div className="flex items-center gap-3 mb-6">
            <div className="bg-primary/10 p-2 rounded-full">
              <AlertCircle className="w-5 h-5 text-primary" />
            </div>
            <h2 className="text-2xl font-semibold">Disclosure of Your Information</h2>
          </div>
          
          <div className="prose prose-lg max-w-none text-gray-700">
            <p>
              We may share information we have collected about you in certain situations. Your information may be disclosed as follows:
            </p>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">By Law or to Protect Rights</h3>
            <p>
              If we believe the release of information about you is necessary to respond to legal process, to investigate or remedy potential violations of our policies, or to protect the rights, property, and safety of others, we may share your information as permitted or required by any applicable law, rule, or regulation.
            </p>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">Third-Party Service Providers</h3>
            <p>
              We may share your information with third parties that perform services for us or on our behalf, including payment processing, data analysis, email delivery, hosting services, customer service, and marketing assistance.
            </p>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">Marketing Communications</h3>
            <p>
              With your consent, or with an opportunity for you to withdraw consent, we may share your information with third parties for marketing purposes.
            </p>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">Business Partners</h3>
            <p>
              We may share your information with our business partners to offer you certain products, services or promotions.
            </p>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">Anonymous Aggregated Data</h3>
            <p>
              We may share your information after it has been aggregated or anonymized, removing any personally identifiable information.
            </p>
          </div>
        </div>
      </div>

      {/* Data Security */}
      <div className="px-4 sm:px-20 xl:px-32 py-12 bg-white">
        <div className="max-w-3xl mx-auto">
          <div className="flex items-center gap-3 mb-6">
            <div className="bg-primary/10 p-2 rounded-full">
              <Shield className="w-5 h-5 text-primary" />
            </div>
            <h2 className="text-2xl font-semibold">Security of Your Information</h2>
          </div>
          
          <div className="prose prose-lg max-w-none text-gray-700">
            <p>
              We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse.
            </p>
            <p>
              Any information disclosed online is vulnerable to interception and misuse by unauthorized parties. Therefore, we cannot guarantee complete security if you provide personal information.
            </p>
          </div>
        </div>
      </div>

      {/* Contact Information */}
      <div className="px-4 sm:px-20 xl:px-32 py-12 bg-gray-50">
        <div className="max-w-3xl mx-auto">
          <div className="flex items-center gap-3 mb-6">
            <div className="bg-primary/10 p-2 rounded-full">
              <Lock className="w-5 h-5 text-primary" />
            </div>
            <h2 className="text-2xl font-semibold">Contact Us</h2>
          </div>
          
          <div className="prose prose-lg max-w-none text-gray-700">
            <p>
              If you have questions or comments about this Privacy Policy, please contact us at:
            </p>
            
            <div className="bg-white p-6 rounded-lg shadow-sm my-6">
              <p>
                <strong>QuickAI Inc.</strong><br />
                Dharan, Sunsari<br />
                Nepal<br />
                <br />
                <strong>Email:</strong> aayushsinghrajput3003@gmail.com<br />
                <strong>Phone:</strong> +977 (980) 598-1168
              </p>
            </div>
          </div>
        </div>
      </div>
      
      <Footer />
    </>
  );
};

export default PrivacyPolicy;